Repository geekymeeky/e-bureau, pull requests merged in 2021-12, with the labels that each got.

#16 Update .gitignore
  .env
  .gitignore
Labels: SWOC, Level 0

#17 Updated the issue templates for bug report, feature request and proposal.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: SWOC, Level 2

#21 signup page with email verification
  components/Header/Header.js
  models/signup.js
  package-lock.json
  package.json
  pages/api/signup/index.js
  pages/api/signup/nodemailer.js
  pages/signup/handleSignup.js
  pages/signup/index.js
  utils/generateOTP.js
  utils/passwordValidator.js
  yarn.lock
Labels: SWOC, Level 2

#25 Update README.md
  README.md
  asset/index.module.css
  pages/index.js
Labels: Level 0
