Repository geekymeeky/e-bureau, pull requests merged in 2022-04, with the labels that each got.

#80 Consistency in UI
  asset/css/index.module.css
  package-lock.json
  pages/AboutUs/index.js
  pages/Dashboard/index.js
  pages/GeneralDiary/Complain.js
  pages/GeneralDiary/index.js
  pages/Missing/Complain.js
  pages/Missing/index.js
  pages/crime/Complain.js
  pages/crime/index.js
Labels: Level2, GSSoC22

#79 Redesigned Input box UI of General Diary, Missing Report, Crime Report pages
  pages/GeneralDiary/index.js
  pages/Missing/index.js
  pages/crime/index.js
Labels: Level2, GSSoC22

#88 Added formik and Yup for validation before sign-in and sign-up
  asset/js/handleSignup.js
  package.json
  pages/signin/index.js
  pages/signup/index.js
Labels: Level2, GSSoC22

#86 Added Workflows
  .github/workflows/Auto_assigner.yml
  .github/workflows/Auto_message_on_PR_open.yml
  .github/workflows/pr_labeler
Labels: Level1, GSSoC22

#92 Added Google Auth Facility
  components/Header/Header.js
  components/Header/Header.module.css
  components/Navbar/Navbar.js
  components/Servies/Services.js
  package-lock.json
  package.json
  pages/index.js
  tailwind.config.js
Labels: Level3, GSSoC22

#94 Live Integration bot Added
  asset/Images/banner.jpg
  asset/Images/chain.png
  asset/Images/icon.png
  asset/Images/people.svg
  asset/Images/phoot.png
  asset/Images/photot.png
  asset/Images/prisoner.png
  asset/Images/stat.svg
  components/ChatwootWidget.js
  package-lock.json
  package.json
  pages/_app.js
  yarn.lock
Labels: Level3, GSSoC22

#93 Added client side validation on Complain and missing report page
  package-lock.json
  package.json
  pages/GeneralDiary/Complain.js
  pages/GeneralDiary/index.js
  pages/Missing/Complain.js
  pages/Missing/index.js
Labels: Level1, GSSoC22
