Repository geekymeeky/e-bureau, pull requests merged in 2022-01, with the labels that each got.

#29 Added contributors section in readme
  README.md
Labels: Level 0

#30 updated ReadMe
  README.md
Labels: Level 1

#38 Debugged - Register Here (Redirecting)
  README.md
  pages/signin/index.js
Labels: SWOC, Level 1

#42 Final Updated README.md with how to setup locally guide.
  README.md
Labels: SWOC, Level 2
